### ISSUE TITLE
Scrolling UI issue

### ISSUE THREAD

**Issue by OR13** [centrehq/verite#374] opened 2022-02-24 13:58 UTC
https://docs.centre.io/verite/developers/issue-a-verifiable-credential

I cannot scroll content on chrome Version 98.0.4758.102 (Official Build) (x86_64) / macOS

**Comment by bricestacey** [comment] 2022-02-24 14:58
I cannot reproduce. I'm on same version, M1 chip.

**Comment by polluterofminds** [comment] 2022-04-28 12:14
Closing as not reproducible.

**Closed by polluterofminds** 2022-04-28 12:14 UTC
